
# This is for testing the ndb_user module !!
# Note: This playbook is only to illustrate all module functionality.
---
- name: NDB_User Module Test
  hosts: ndb
  gather_facts: yes
  connection: local
  collections:
    - sgerhart.ndb
  tasks:
  - name: Create User
    ndb_user:
      ndb_host: "{{ inventory_hostname }}"
      ndb_port: 8443
      ndb_username: admin
      ndb_password: admin
      state: present
      username: testuser17
      password: C!sco#123
      role: Network-Admin
    register: testout
  - name: Results Dump
    debug:
      msg: '{{ testout }}'